name: deeplabcut-with-tf
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - libexpat=2.7.3
  - libffi=3.4.4
  - libzlib=1.3.1
  - openssl=3.0.18
  - pip=25.3
  - python=3.10.19
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  #- ucrt=10.0.22621.0
  #- vc=14.3
  #- vc14_runtime=14.44.35208
  #- vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - alabaster==0.7.16
      - albumentations==1.4.3
      - altair==6.0.0
      - anyio==4.12.0
      - app-model==0.2.8
      - appdirs==1.4.4
      - asttokens==3.0.1
      - astunparse==1.6.3
      - attrs==25.4.0
      - babel==2.17.0
      - blinker==1.9.0
      - blosc2==3.12.2
      - build==1.3.0
      - cachetools==6.2.4
      - cachey==0.2.1
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - click==8.3.1
      - cloudpickle==3.1.2
      - colorama==0.4.6
      - comm==0.2.3
      - contourpy==1.3.2
      - cycler==0.12.1
      - dask==2025.12.0
      - dask-image==2025.11.0
      - debugpy==1.8.19
      - decorator==5.2.1
      - deeplabcut==3.0.0rc13
      - dlclibrary==0.0.11
      - docstring-parser==0.17.0
      - docutils==0.17.1
      - einops==0.8.1
      - exceptiongroup==1.3.1
      - executing==2.2.1
      - filelock==3.20.0
      - filterpy==1.4.5
      - flatbuffers==25.12.19
      - flexcache==0.3
      - flexparser==0.4
      - fonttools==4.61.1
      - freetype-py==2.5.1
      - fsspec==2025.12.0
      - gast==0.4.0
      - gitdb==4.0.12
      - gitpython==3.1.46
      - google-auth==2.45.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.76.0
      - h11==0.16.0
      - h5py==3.15.1
      - heapdict==1.0.1
      - hf-xet==1.2.1rc0
      - hsluv==5.0.4
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.2.3
      - idna==3.11
      - imageio==2.37.2
      - imageio-ffmpeg==0.6.0
      - imagesize==1.4.1
      - imgaug==0.4.0
      - importlib-metadata==8.7.1
      - in-n-out==0.2.1
      - intel-openmp==2021.4.0
      - ipykernel==6.31.0
      - ipython==8.37.0
      - ipython-pygments-lexers==1.1.1
      - jax==0.4.30
      - jaxlib==0.4.30
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.3
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-client==8.7.0
      - jupyter-core==5.9.1
      - keras==2.12.0
      - kiwisolver==1.4.10rc0
      - lazy-loader==0.4
      - libclang==18.1.1
      - llvmlite==0.46.0
      - locket==1.0.0
      - magicgui==0.10.1
      - markdown==3.10
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.8.4
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - mkl==2021.4.0
      - ml-dtypes==0.5.4
      - mpmath==1.3.0
      - msgpack==1.1.2
      - msgpack-numpy==0.4.8
      - napari==0.4.18
      - napari-console==0.1.4
      - napari-deeplabcut==0.2.1.7
      - napari-plugin-engine==0.2.0
      - napari-svg==0.2.1
      - narwhals==2.15.0
      - natsort==8.4.0
      - ndindex==1.10.1
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - npe2==0.7.9
      - numba==0.63.1
      - numexpr==2.14.1
      - numpy==1.26.4
      - numpydoc==1.5.0
      - oauthlib==3.3.1
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - opt-einsum==3.4.0
      - packaging==25.0
      - pandas==2.3.3
      - parso==0.8.5
      - partd==1.4.2
      - patsy==1.0.2
      - pillow==12.0.0
      - pims==0.7
      - pint==0.24.4
      - platformdirs==4.5.1
      - pooch==1.8.2
      - prompt-toolkit==3.0.52
      - protobuf==4.25.8
      - psutil==7.1.3
      - psygnal==0.15.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pyarrow==22.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycocotools==2.0.11
      - pyconify==0.2.1
      - pydantic==1.10.26
      - pydantic-compat==0.1.2
      - pydeck==0.9.1
      - pygments==2.19.2
      - pyopengl==3.1.10
      - pyparsing==3.3.1
      - pyproject-hooks==1.2.0
      - pyside6==6.10.1
      - pyside6-addons==6.10.1
      - pyside6-essentials==6.10.1
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - qdarkstyle==3.1
      - qtconsole==5.7.0
      - qtpy==2.4.3
      - referencing==0.37.0
      - requests==2.32.5
      - requests-oauthlib==2.0.0
      - rich==14.2.0
      - rpds-py==0.30.0
      - rsa==4.9.1
      - ruamel-yaml==0.18.17
      - ruamel-yaml-clib==0.2.15
      - safetensors==0.7.0
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - shapely==2.1.2
      - shellingham==1.5.4
      - shiboken6==6.10.1
      - six==1.17.0
      - slicerator==1.1.0
      - smmap==5.0.2
      - snowballstemmer==3.0.1
      - sphinx==4.5.0
      - sphinxcontrib-applehelp==2.0.0
      - sphinxcontrib-devhelp==2.0.0
      - sphinxcontrib-htmlhelp==2.1.0
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==2.0.0
      - sphinxcontrib-serializinghtml==2.0.0
      - stack-data==0.6.3
      - statsmodels==0.14.6
      - streamlit==1.52.2
      - superqt==0.7.6
      - sympy==1.14.0
      - tables==3.10.1
      - tabulate==0.9.0
      - tbb==2021.13.1
      - tenacity==9.1.2
      - tensorboard==2.12.3
      - tensorboard-data-server==0.7.2
      - tensorflow==2.12.0
      - tensorflow-estimator==2.12.0
      - tensorflow-intel==2.12.0
      - tensorflow-io-gcs-filesystem==0.31.0
      - tensorpack==0.11
      - termcolor==3.2.0
      - tf-slim==1.1.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timm==1.0.22
      - toml==0.10.2
      - tomli==2.3.0
      - tomli-w==1.2.0
      - toolz==1.1.0
      - torch==2.3.1
      - torchvision==0.18.1
      - tornado==6.5.4
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typer==0.20.1
      - typer-slim==0.20.1
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - urllib3==2.6.2
      - vispy==0.12.2
      - watchdog==6.0.0
      - wcwidth==0.2.14
      - werkzeug==3.1.4
      - wrapt==1.14.2
      - zipp==3.23.0
#prefix: C:\Users\oheun\anaconda3\envs\deeplabcut-with-tf
